import pluginMicrosoftSdl from "@microsoft/eslint-plugin-sdl"
import nodePlugin from "eslint-plugin-n"
import pluginSecurity from "eslint-plugin-security"
import { defineConfig } from "oxlint"

const mergeRules = (
  left: { rules: Record<string, string> },
  right: { rules: Record<string, string> },
) => ({ rules: { ...left.rules, ...right.rules } })

export default defineConfig({
  $schema   : "./node_modules/oxlint/configuration_schema.json",
  categories: {
    correctness: "warn",
    nursery    : "warn",
    pedantic   : "warn",
    perf       : "warn",
    restriction: "warn",
    style      : "warn",
    suspicious : "warn",
  },
  jsPlugins: [
    "@stylistic/eslint-plugin",
    "eslint-plugin-align-assignments",
    "eslint-plugin-sonarjs",
    "eslint-plugin-perfectionist",
    "@microsoft/eslint-plugin-sdl",
    "eslint-plugin-n",
    "eslint-plugin-security",
    "eslint-plugin-array-func",
  ],
  overrides: [
    {
      files: ["*.astro", "*.svelte"],
      rules: {
        "no-unused-vars": "off",
      },
    },
  ],
  plugins: [
    "typescript",
    "unicorn",
    "oxc",
    "import",
    "jsdoc",
    "vue",
    "eslint",
    "node",
    "promise",
  ],
  rules: {
    "@stylistic/indent"                : 0,
    "@stylistic/jsx-self-closing-comp" : 1,
    "@stylistic/key-spacing"           : [1, { align: {}, multiLine: {} }],
    "@stylistic/member-delimiter-style": [
      1,
      {
        multiline: {
          delimiter: "none",
        },
      },
    ],
    ...nodePlugin.configs["flat/recommended-script"].rules,
    ...pluginMicrosoftSdl.configs.recommended.reduce(mergeRules).rules,
    ...pluginSecurity.configs.recommended.rules,
    "align-assignments/align-assignments"             : 1,
    "array-type"                                      : 0,
    "capitalized-comments"                            : 0,
    "consistent-type-exports"                         : 0,
    "eslint-plugin-import/group-exports"              : 0,
    "eslint-plugin-import/no-anonymous-default-export": 0,
    "eslint-plugin-import/no-named-export"            : 0,
    "eslint-plugin-import/unambiguous"                : 0,
    "eslint-plugin-promise/avoid-new"                 : 0,
    "eslint-plugin-promise/prefer-await-to-callbacks" : 0,
    "eslint-plugin-promise/prefer-await-to-then"      : 0,
    "explicit-function-return-type"                   : 0,
    "exports-last"                                    : 0,
    "filename-case"                                   : 0,
    "max-depth"                                       : [
      2,
      {
        max: 4,
      },
    ],
    "max-lines-per-function": [
      1,
      {
        IIFEs         : true,
        max           : 50,
        skipBlankLines: true,
        skipComments  : true,
      },
    ],
    "n/no-missing-import"                      : 0,
    "n/no-process-exit"                        : 0,
    "eslint-plugin-import/no-default-export"   : 0,
    "no-async-await"                           : 0,
    "no-optional-chaining"                     : 0,
    "no-rest-spread-properties"                : 0,
    "no-ternary"                               : 0,
    "no-undef"                                 : 0,
    "no-undefined"                             : 0,
    "no-useless-default-assignment"            : 0,
    "prefer-default-export"                    : 0,
    "sonarjs/array-constructor"                : 1,
    "sonarjs/prefer-immediate-return"          : 1,
    "sort-imports"                             : 0,
    "strict-void-return"                       : 0,
    "typescript/explicit-module-boundary-types": 0,
    "typescript/no-floating-promises"          : 0,
    "unicorn/no-array-for-each"                : 0,
    "unicorn/no-null"                          : 0,
    "unicorn/no-useless-spread"                : 0,
    "unicorn/prefer-includes"                  : 0,
    "eslint/new-cap"                           : 0,
    "eslint-plugin-import/no-nodejs-modules"   : 0,
    yoda                                       : 0,
    "array-func/avoid-reverse"                 : 1,
    "array-func/from-map"                      : 1,
    "array-func/no-unnecessary-this-arg"       : 1,
    "array-func/prefer-array-from"             : 1,
    "array-func/prefer-flat"                   : 1,
    "array-func/prefer-flat-map"               : 1,
  },
})
